name: Cypress Spenkey

on: 
 push:
   branches: ["dev"]
 pull_request:
   branches: ["dev"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Build docker image
      - name: build & push docker image
        run: docker build -t spendkey-cypress .  
    
      # Generate output reports in artifcats
      - name: Output of the Reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
         name: TestReport
         path: ./cypress/reports
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        with:
         format: YYYYMMDD-HH
         utcOffset: "+08:00"
      - name: Current date & time  
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
  
