name: Cypress Spenkey

on: 
 push:
   branches: ["dev"]
 pull_request:
   branches: ["dev"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Build docker image
      - name: build & push docker image
        run: docker build -t spendkey-cypress . 
        
      - name: Set Time
        run: |
         echo "date=$(date +"%Y-%m-%d")" >> $GITHUB_ENV  
         echo "MY_DATE=$(date +"%H:%M:%S")" >> $GITHUB_ENV
         
      # Generate output reports in artifcats
      - name: Output of the Reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
         name: TestReport ${{env.MY_DATE}}
         path: ./cypress/reports
  
