name: Cypress Spenkey

on: 
 push:
   branches: ["dev"]
 pull_request:
   branches: ["dev"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Build & Run the docker image
      - name: build & push image
        run: docker build -t spendkey .   
      
      # Install NPM dependencies, cache them correctly     
      # - name: Install all dependencies
      #   run: npm install
      
      # Generate output reports in artifcats
      - name: Output of the Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
         name: TestReport
         path: ./cypress/reports
