name: Cypress Spenkey

on: 
 push:
   branches: ["dev"]
 pull_request:
   branches: ["dev"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Run the docker image
      
      # Build & Run the docker image
      - name: build & push image
        run: docker build -t spendkey-cypress .

      # - name: run docker image
      #   run: docker-compose run e2e-chrome   
      
      - name: Generate report
        continue-on-error: true
        uses: cypress-io/github-action@v4.2.0
        with:
         start: node cypress_test_reports.js    


      # Generate output reports in artifcats
      - name: Output of the Reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
         name: TestReport
         path: ./cypress/reports
