# name: Cypress Spenkey

# on: 
#  push:
#    branches: ["dev"]
#  pull_request:
#    branches: ["dev"]

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       # Build the docker image   
#       - name: Build the docker image  
#         run: docker build -t spendkey-cypress .

#       # Run the docker image
#       - name: Run the docker image
#         run: docker-compose run e2e-chrome  
#       # Install NPM dependencies, cache them correctly     
#       # - name: Install all dependencies
#       #   run: npm install
        
#       # Run specflow headless
#       # - name: Cypress run
#       #   run: npx cypress run --config baseUrl=https://demo.spendkey.app/dashboard
      
#       # Generate output reports in artifcats
#       - name: Output of the Reports
#         if: always()
#         uses: actions/upload-artifact@v3
#         with:
#          name: TestReport
#          path: ./cypress/reports



  name: Cypress project

  on: 
    push:
      branches: ["dev"]
    pull_request:
      branches: ["dev"]

  jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3
       
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build & push image
        run: docker build -t spendkey-cypress .

      - name: run docker image
        run: docker-compose run e2e-chrome    

   Generate output reports in artifcats
     - name: Output of the Reports
       if: always()
       uses: actions/upload-artifact@v3
       with:
        name: TestReport
        path: ./cypress/reports