name: Cypress Spenkey

on: 
 push:
   branches: ["dev"]
 pull_request:
   branches: ["dev"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Build docker image
      - name: build & push docker image
        run: docker build -t spendkey-cypress .

      - name: run api tests
        run: docker-compose run api-test
        
      - name: Set Time
        run: |
         echo "date=$(date +"%Y-%m-%d-%H-%M-%S")" >> $GITHUB_ENV   
        
      # Generate output reports in artifcats
      - name: Output Reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
         name: API Report ${{env.date}}
         path: ./cypress/reports  
        
        
      - name: run ui tests
        run: docker-compose run ui-test
        
      - name: Set Time
        run: |
         echo "date=$(date +"%Y-%m-%d")" >> $GITHUB_ENV  
        
      # Generate output reports in artifcats
      - name: Output Reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
         name: UI Report ${{env.date}}
         path: ./cypress/reports
  
